import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowUpRight, BriefcaseBusiness, CircleDollarSign, RefreshCw, Sparkles, Target } from "lucide-react";
import type { Deal } from "@/data/deals";
import { deals, money, weightedPipeline } from "@/data/deals";
import { Button } from "@/components/ui/button";
import { DealCard } from "@/components/win-deals/deal-card";
import { EmailDialog } from "@/components/win-deals/email-dialog";
import { pageMeta } from "@/components/win-deals/page-meta";

export const Route = createFileRoute("/app/dashboard")({ head:()=>pageMeta("Deal Command Center","Prioritized deal intelligence and pipeline health for WIN DEALS."), component: Dashboard });
function Dashboard(){
 const [draft,setDraft]=useState<Deal>(); const [refreshed,setRefreshed]=useState(false);
 const attention=deals.filter(d=>d.health!=="Healthy").sort((a,b)=>a.score-b.score).slice(0,5);
 const metrics=[{label:"Active Deals",value:"27",note:"4 added this month",icon:BriefcaseBusiness},{label:"Pipeline Value",value:"$486,000",note:"↑ 8.2% this month",icon:CircleDollarSign},{label:"Weighted Pipeline",value:money(weightedPipeline),note:"64% forecast coverage",icon:Target},{label:"Needs Attention",value:"5",note:"2 critical this week",icon:ArrowUpRight,attention:true}];
 return <><header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-semibold text-primary">Wednesday, October 7</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">Deal Command Center</h1><p className="mt-1 text-secondary-foreground">Here’s what needs your attention today.</p></div><Button variant="outline" onClick={()=>{setRefreshed(true);setTimeout(()=>setRefreshed(false),1800)}}><RefreshCw className={refreshed?"animate-spin":""}/>{refreshed?"Up to date":"Refresh"}</Button></header>
 <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({label,value,note,icon:Icon,attention})=><div key={label} className={`rounded-lg border bg-card p-5 shadow-card ${attention?"border-critical/30":"border-border"}`}><div className="flex items-center justify-between"><span className="text-sm font-medium text-secondary-foreground">{label}</span><span className={`grid size-8 place-items-center rounded-lg ${attention?"bg-critical-soft text-critical":"bg-brand-soft text-primary"}`}><Icon className="size-4"/></span></div><div className="mt-3 text-2xl font-bold tabular-nums">{value}</div><p className={`mt-1 text-xs ${attention?"text-critical":"text-muted-foreground"}`}>{note}</p></div>)}</section>
 <div className="mt-7 grid gap-6 xl:grid-cols-[minmax(0,1.6fr)_minmax(290px,.7fr)]"><section><div className="mb-3 flex items-end justify-between"><div><h2 className="text-lg font-semibold">Priority Queue</h2><p className="text-sm text-muted-foreground">Prioritized by deal risk and impact.</p></div><span className="text-xs text-muted-foreground">Showing top 5</span></div><div className="space-y-3">{attention.map(d=><DealCard key={d.id} deal={d} onDraft={setDraft}/>)}</div></section><aside className="space-y-4"><div className="rounded-lg border border-border bg-card p-5 shadow-card"><h2 className="font-semibold">Pipeline Health</h2><p className="mt-1 text-sm text-muted-foreground">27 active deals</p><div className="mt-5 flex h-3 overflow-hidden rounded-full"><span className="w-[52%] bg-healthy"/><span className="w-[26%] bg-risk"/><span className="w-[22%] bg-critical"/></div><div className="mt-5 space-y-3">{[["Healthy","14","bg-healthy"],["At Risk","7","bg-risk"],["Critical","6","bg-critical"]].map(x=><div key={x[0]} className="flex items-center text-sm"><span className={`mr-2 size-2 rounded-full ${x[2]}`}/><span className="flex-1 text-secondary-foreground">{x[0]}</span><strong>{x[1]}</strong></div>)}</div></div><div className="rounded-lg border border-primary/20 bg-brand-soft p-5"><div className="flex items-center gap-2 text-primary"><Sparkles className="size-4"/><span className="text-xs font-bold uppercase">AI Pipeline Insight</span></div><p className="mt-4 text-lg font-semibold leading-snug">23% of your active pipeline has had no meaningful activity in the last 7 days.</p><p className="mt-3 text-sm leading-relaxed text-secondary-foreground">Re-engaging these deals this week could protect up to $112,000 in pipeline.</p></div></aside></div>
 <EmailDialog deal={draft} open={!!draft} onOpenChange={o=>!o&&setDraft(undefined)}/></>;
}
