import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { ArrowRight, Search } from "lucide-react";
import { deals, money, type DealHealth } from "@/data/deals";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { HealthBadge } from "@/components/win-deals/health-badge";
import { WinScore } from "@/components/win-deals/score";
import { pageMeta } from "@/components/win-deals/page-meta";
import { cn } from "@/lib/utils";
export const Route=createFileRoute("/app/deals/")({head:()=>pageMeta("Deals","Search and prioritize every active deal in WIN DEALS."),component:DealsPage});
function DealsPage(){const [q,setQ]=useState("");const [filter,setFilter]=useState<"All"|DealHealth>("All");const rows=useMemo(()=>deals.filter(d=>(filter==="All"||d.health===filter)&&d.name.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>a.score-b.score),[q,filter]);const filters:[["All"|DealHealth,number]][number][]=[["All",27],["Healthy",14],["At Risk",7],["Critical",6]];
return <><header><h1 className="text-2xl font-bold sm:text-3xl">Deals</h1><p className="mt-1 text-secondary-foreground">Your pipeline, prioritized by what needs action first.</p></header><div className="mt-6 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="relative w-full max-w-md"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="h-10 bg-card pl-9" placeholder="Search deals..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="flex gap-2 overflow-x-auto pb-1">{filters.map(([label,count])=><Button key={label} size="sm" variant={filter===label?"default":"outline"} onClick={()=>setFilter(label)}>{label}<span className={cn("rounded px-1.5 text-[10px]",filter===label?"bg-primary-foreground/15":"bg-muted")}>{count}</span></Button>)}</div></div>
<div className="mt-5 overflow-hidden rounded-xl border border-border bg-card shadow-card"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left"><thead className="border-b border-border bg-muted/50 text-xs uppercase text-muted-foreground"><tr><th className="px-5 py-3 font-semibold">Deal</th><th className="px-4 py-3 font-semibold">Value</th><th className="px-4 py-3 font-semibold">Stage</th><th className="px-4 py-3 font-semibold">WIN Score™</th><th className="px-4 py-3 font-semibold">Health</th><th className="px-4 py-3 font-semibold">Next Best Action</th><th className="px-5 py-3"/></tr></thead><tbody>{rows.map(d=><tr key={d.id} className="border-b border-border last:border-0 hover:bg-muted/40"><td className="px-5 py-4"><Link to="/app/deals/$id" params={{id:d.id}} className="font-semibold hover:text-primary">{d.name}</Link><div className="mt-0.5 text-xs text-muted-foreground">Owner: {d.owner}</div></td><td className="px-4 py-4 text-sm font-semibold tabular-nums">{money(d.value)}</td><td className="px-4 py-4 text-sm text-secondary-foreground">{d.stage}</td><td className="px-4 py-4"><WinScore score={d.score}/></td><td className="px-4 py-4"><HealthBadge health={d.health}/></td><td className="max-w-xs px-4 py-4 text-sm text-secondary-foreground">{d.nextAction}</td><td className="px-5 py-4"><Button variant="ghost" size="sm" asChild><Link to="/app/deals/$id" params={{id:d.id}}>View<ArrowRight/></Link></Button></td></tr>)}</tbody></table></div>{rows.length===0&&<div className="p-10 text-center text-sm text-muted-foreground">No deals match your search.</div>}</div></>}
