import hubspotLogo from "@/assets/logos/hubspot.svg";
import claudeLogo from "@/assets/logos/brands/claude.svg";
import openaiLogo from "@/assets/logos/brands/openai.svg";
import salesforceLogo from "@/assets/logos/brands/salesforce.svg";
import zohoLogo from "@/assets/logos/brands/zoho.svg";
import microsoftLogo from "@/assets/logos/brands/microsoft.svg";
import { ArrowDown, ArrowRight, Calculator, Database, FileText, Gauge, Layers, Sparkles, Target, UserCheck } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { Logo } from "@/components/win-deals/logo";
import { cn } from "@/lib/utils";
import { Heading, section, wrap } from "./home-sections";
import { Reveal } from "./reveal";

/** Status labels must match what the product actually does today. */
type Status = "In development" | "Planned" | "Architecture-ready";
function StatusPill({ status, strong }: { status: Status; strong?: boolean }) {
  return <span className={cn("rounded-full border px-2.5 py-0.5 text-[11px] font-semibold", strong ? "border-primary/30 bg-brand-soft text-primary" : "border-border bg-muted text-secondary-foreground")}>{status}</span>;
}

const deterministic = ["Deal age", "Days since last activity", "Activity frequency", "Stage duration", "Meeting activity", "Email activity", "Stakeholder engagement", "Contact coverage", "Buying-signal patterns", "Pipeline movement", "Inactivity", "Close-date changes"];
const aiQuestions = ["What is happening?", "Why does this deal need attention?", "What changed?", "What is the likely risk?", "What should the salesperson do next?", "What message could they send?"];

export function AIExplained() {
  const flow = [
    { icon: Database, t: "CRM data", d: "Deals, contacts, activities, stages" },
    { icon: Calculator, t: "WIN DEALS signal engine", d: "Objective facts, calculated by software" },
    { icon: Gauge, t: "WIN Score + deal health", d: "Explainable measurement — no AI involved" },
    { icon: Sparkles, t: "AI reasoning", d: "Claude interprets signals and context", ai: true },
    { icon: FileText, t: "Deal diagnosis", d: "What is happening and why", ai: true },
    { icon: Target, t: "Next Best Action", d: "One recommended step, plus an optional draft", ai: true },
    { icon: UserCheck, t: "Sales rep", d: "Reviews, decides and acts", focus: true },
  ];
  return <section id="ai" className={cn(section, "scroll-mt-16 border-y border-border bg-card")}><div className={wrap}>
    <Heading eyebrow="Where AI is used" title="AI that explains the pipeline — not just scores it." body="Software measures. AI interprets. The WIN Score is calculated from objective CRM signals, so it is consistent and explainable. AI is used afterwards to reason about those signals and turn them into a diagnosis and a next step." />
    <div className="mt-12 grid gap-4 lg:grid-cols-2">
      <Reveal><div className="h-full rounded-xl border border-border bg-background p-6 sm:p-7">
        <div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-brand-soft text-primary"><Calculator className="size-5" aria-hidden /></span><div><div className="text-xs font-bold uppercase tracking-wider text-primary">Deterministic intelligence</div><h3 className="text-lg font-semibold">Software calculates the facts</h3></div></div>
        <ul className="mt-5 flex flex-wrap gap-2">{deterministic.map((t) => <li key={t} className="rounded-md border border-border bg-card px-2.5 py-1 text-sm">{t}</li>)}</ul>
        <p className="mt-5 border-t border-border pt-4 text-sm text-secondary-foreground">These signals feed the <strong className="text-foreground">WIN Score</strong> and <strong className="text-foreground">deal health</strong>. The score is never generated by a language model.</p>
      </div></Reveal>
      <Reveal delay={100}><div className="h-full rounded-xl border border-ai/20 bg-ai-soft p-6 sm:p-7">
        <div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-lg bg-card text-ai"><Sparkles className="size-5" aria-hidden /></span><div><div className="text-xs font-bold uppercase tracking-wider text-ai">AI intelligence</div><h3 className="text-lg font-semibold">AI interprets what the facts mean</h3></div></div>
        <ul className="mt-5 grid gap-2 sm:grid-cols-2">{aiQuestions.map((q) => <li key={q} className="rounded-md border border-ai/15 bg-card px-3 py-2 text-sm font-medium">{q}</li>)}</ul>
        <p className="mt-5 border-t border-ai/15 pt-4 text-sm text-secondary-foreground"><strong className="text-foreground">AI recommends. Salespeople decide.</strong> Every suggestion is reviewable; nothing is sent or changed automatically.</p>
      </div></Reveal>
    </div>
    <ol className="mt-12 grid gap-2 lg:grid-cols-7" aria-label="How a deal moves from CRM data to action">
      {flow.map((f, i) => <Reveal key={f.t} delay={i * 90}><li className="relative flex h-full flex-col">
        <div className={cn("flex h-full flex-col rounded-lg border p-4 transition-shadow hover:shadow-card", f.focus ? "border-primary bg-brand-soft" : f.ai ? "border-ai/20 bg-ai-soft" : "border-border bg-background")}>
          <div className="flex items-center justify-between"><f.icon className={cn("size-4", f.ai ? "text-ai" : "text-primary")} aria-hidden /><span className="text-xs font-semibold tabular-nums text-muted-foreground">0{i + 1}</span></div>
          <div className="mt-3 text-sm font-bold">{f.t}</div>
          <p className="mt-1 text-xs leading-snug text-secondary-foreground">{f.d}</p>
        </div>
        {i < flow.length - 1 && <ArrowDown className="mx-auto my-1 size-4 text-muted-foreground lg:hidden" aria-hidden />}
      </li></Reveal>)}
    </ol>
  </div></section>;
}

export function AIProviders() {
  const providers = [
    { logo: claudeLogo, name: "Claude", by: "Anthropic", role: "Primary AI provider", status: "In development" as Status, strong: true, d: "Designed as the reasoning layer for diagnosis, risk explanations and next-best actions." },
    { logo: openaiLogo, name: "GPT models", by: "OpenAI", role: "Supported provider", status: "Planned" as Status, d: "Can be connected through the same provider interface." },
    { logo: null, name: "OpenAI-compatible APIs", by: "Standard interface", role: "Provider abstraction", status: "Architecture-ready" as Status, d: "Compatible model providers plug into one standard interface." },
  ];
  const outputs = ["Deal diagnosis", "Risk explanations", "Buying-signal interpretation", "Recommended next actions", "Sales-context summaries", "Optional email drafts"];
  return <section className={section}><div className={wrap}>
    <Heading eyebrow="AI architecture" title="Built for the best AI models." body="An abstraction layer keeps the intelligence engine independent of any single AI provider. Claude is the primary reasoning model WIN DEALS is being built around." />
    <div className="mt-12 grid gap-4 md:grid-cols-3">{providers.map((p, i) => <Reveal key={p.name} delay={i * 90}><div className={cn("flex h-full flex-col rounded-xl border bg-card p-6 transition-shadow hover:shadow-card", p.strong ? "border-primary ring-1 ring-primary/20" : "border-border")}>
      <div className="flex items-center justify-between gap-3"><div className="flex items-center gap-3">{p.logo ? <img src={p.logo} alt={`${p.by} logo`} className="size-7" /> : <Layers className="size-7 text-secondary-foreground" aria-hidden />}<div><div className="font-semibold leading-tight">{p.name}</div><div className="text-xs text-muted-foreground">{p.by}</div></div></div><StatusPill status={p.status} strong={p.strong} /></div>
      <div className={cn("mt-5 text-sm font-bold", p.strong ? "text-primary" : "text-foreground")}>{p.role}</div>
      <p className="mt-1.5 text-sm leading-relaxed text-secondary-foreground">{p.d}</p>
    </div></Reveal>)}</div>
    <Reveal><div className="mt-10 grid gap-8 rounded-xl border border-ai/20 bg-ai-soft p-6 sm:p-8 lg:grid-cols-[1fr_1.2fr]">
      <div><div className="flex items-center gap-2 text-ai"><Sparkles className="size-4" aria-hidden /><span className="text-xs font-bold uppercase tracking-wider">Why Claude</span></div><h3 className="mt-3 text-2xl font-bold tracking-tight">Claude powers the reasoning layer.</h3><p className="mt-3 text-secondary-foreground">Claude receives structured deal signals and only the relevant, normalized sales context — never unrestricted access to your CRM. It does not make decisions or send emails.</p></div>
      <div><div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">What it produces</div><ul className="mt-3 grid gap-2 sm:grid-cols-2">{outputs.map((o) => <li key={o} className="rounded-md border border-ai/15 bg-card px-3 py-2 text-sm font-medium">{o}</li>)}</ul></div>
    </div></Reveal>
  </div></section>;
}

export function CRMIntegrations() {
  const next = [
    { name: "Salesforce", logo: salesforceLogo },
    { name: "Pipedrive", logo: null },
    { name: "Close", logo: null },
    { name: "Zoho CRM", logo: zohoLogo },
    { name: "Microsoft Dynamics", logo: microsoftLogo },
  ];
  const arch = ["CRM", "CRM adapter", "WIN DEALS normalized data model", "Intelligence engine"];
  return <section id="integrations" className={cn(section, "scroll-mt-16 border-y border-border bg-card")}><div className={cn(wrap, "grid items-start gap-12 lg:grid-cols-[1.15fr_1fr]")}>
    <div>
      <Heading eyebrow="Integrations" title="Works with the CRM your team already uses." body="Your CRM stays the system of record. Each CRM connects through an adapter into one normalized data model, so the intelligence engine is not hard-coded around a single CRM." />
      <Reveal><div className="mt-8 flex items-center justify-between gap-4 rounded-xl border border-primary bg-background p-5 ring-1 ring-primary/20">
        <div className="flex items-center gap-3"><img src={hubspotLogo} alt="HubSpot logo" className="size-8" /><div><div className="font-semibold">HubSpot</div><div className="text-sm text-primary">Initial CRM integration</div></div></div><StatusPill status="In development" strong />
      </div></Reveal>
      <div className="mt-3 grid gap-2 sm:grid-cols-2">{next.map((c, i) => <Reveal key={c.name} delay={i * 60}><div className="flex items-center justify-between gap-3 rounded-lg border border-border bg-background px-4 py-3">
        <div className="flex items-center gap-2.5">{c.logo ? <img src={c.logo} alt={`${c.name} logo`} className="size-5 opacity-80" /> : <span className="size-5" aria-hidden />}<span className="text-sm font-semibold">{c.name}</span></div><StatusPill status="Planned" />
      </div></Reveal>)}</div>
      <Reveal><div className="mt-8"><Button asChild><Link to="/signup">Join early access <ArrowRight /></Link></Button></div></Reveal>
    </div>
    <Reveal><div className="mx-auto flex w-full max-w-sm flex-col items-center gap-2 rounded-xl border border-border bg-background p-6 sm:p-8">
      {arch.map((a, i) => <div key={a} className="flex w-full flex-col items-center gap-2">
        <div className={cn("flex w-full items-center justify-center rounded-lg border px-4 py-3.5 text-center text-sm font-semibold", i === 3 ? "border-ai/20 bg-ai-soft text-ai" : i === 2 ? "border-primary/30 bg-brand-soft" : "border-border bg-card")}>
          {i === 0 ? <span className="flex items-center gap-2"><img src={hubspotLogo} alt="" className="size-5" />HubSpot · other CRMs</span> : i === 2 ? <span className="flex flex-col items-center gap-1"><Logo /><span className="text-xs font-medium text-secondary-foreground">Normalized data model</span></span> : i === 3 ? <span className="flex items-center gap-2"><Sparkles className="size-4" aria-hidden />{a}</span> : a}
        </div>
        {i < arch.length - 1 && <ArrowDown className="size-4 text-muted-foreground" aria-hidden />}
      </div>)}
    </div></Reveal>
  </div></section>;
}
